# Generated by Django 4.1.7 on 2023-03-01 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0012_applyjob_job'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ApplyJob',
        ),
    ]
