# Generated by Django 4.1.7 on 2023-03-01 16:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0014_apply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Apply',
        ),
    ]
