# Generated by Django 4.1.7 on 2023-03-01 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('job', '0017_apply_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='apply',
            name='create',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
